<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CommentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('comment')->insert([
            [
                'forum_id' => 'FOM1',
                'comment_id' => 'COM1',
                'user_id' => 'EST2',
                'contents' =>  '<p>Trust your process and dont break your own rules.</p>',
                'created_at' => Carbon::now()->subDay(4)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM1',
                'comment_id' => 'COM2',
                'user_id' => 'EST3',
                'contents' =>  "<p>Don't try to punch the market. The harder you hit, the more you'll feel. That mindset change from what you want the market to do, to what the market could offer you.</p>",
                'created_at' => Carbon::now()->subDay(3)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM1',
                'comment_id' => 'COM3',
                'user_id' => 'EST4',
                'contents' =>  "<p>Mine has been learning about the different cognitive biases that affect our actions and thoughts, such as the gambler's fallacy, attentional bias, confirmation bias, etc. It made me more aware of the patterns in my thinking and my emotions which helps me stay rational.</p>",
                'created_at' => Carbon::now()->subDay(2)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM2',
                'comment_id' => 'COM4',
                'user_id' => 'EST4',
                'contents' =>  "<p>Forex trading was very difficult for me at first, especially the aspect of trading terminologies and following my trading strategy; trading has become a lot easier for me now. The more I trade, the easier it becomes.</p>",
                'created_at' => Carbon::now()->subDay(2)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM3',
                'comment_id' => 'COM5',
                'user_id' => 'EST6',
                'contents' =>  "<p>Yes of course, mistake is my best teacher. Now, i'm able to WD some dollar from my lovely broker liteforex. in a month i can WD $200.Keep learning and keep focus...</p>",
                'created_at' => Carbon::now()->subDay(3)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM4',
                'comment_id' => 'COM6',
                'user_id' => 'EST4',
                'contents' =>  "<p>Well done, especially Point #4. The best traders are the ones who have patience and persevere, unlike the nervous and impulsive rookies!</p>",
                'created_at' => Carbon::now()->subDay(1)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM4',
                'comment_id' => 'COM7',
                'user_id' => 'EST5',
                'contents' =>  "<p>We could put in patience in between 3 and 4 because it's one of the most important things to have for a trader.</p>",
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM4',
                'comment_id' => 'COM8',
                'user_id' => 'EST6',
                'contents' =>  "<p>I also agreed with these points!</p>",
                'created_at' => Carbon::now()->subDay(3)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM5',
                'comment_id' => 'COM9',
                'user_id' => 'EST1',
                'contents' =>  "<p>Spreads vary, depending on the quotes from the other traders, financial news, global cues and the demand..I could provide a long explanation but essentially, this is why spreads vary by the second.</p>",
                'created_at' => Carbon::now()->subDay(5)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM5',
                'comment_id' => 'COM10',
                'user_id' => 'EST3',
                'contents' =>  "<p>Variable spreads depend on the price feed generated by your broker's liquidity providers. The feed is based on the actual limit and stop orders placed in the market + broker's markup (profit).</p>",
                'created_at' => Carbon::now()->subDay(11)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM6',
                'comment_id' => 'COM11',
                'user_id' => 'EST5',
                'contents' =>  "<p>Tight spreads are very necessary if a trade wish to make long term profits on platform. The brokers that offer very tight spreads are ECN/STP and a few market makers.</p>",
                'created_at' => Carbon::now()->subDay(7)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM6',
                'comment_id' => 'COM12',
                'user_id' => 'EST3',
                'contents' =>  "<p>One of the key factors that play an important role in determining the profitability of trading Forex spread cost of trade transactions with greater spread, which is offered by Forex brokers Forex what affect ...</p>",
                'created_at' => Carbon::now()->subDay(8)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM7',
                'comment_id' => 'COM13',
                'user_id' => 'EST1',
                'contents' =>  "<p>Of course, any new trader can learn Forex by demo practice! But, it’s not shortcut way; generally it takes such a long time to learn! This is why, having a long term plan is very much important.</p>",
                'created_at' => Carbon::now()->subDay(2)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM7',
                'comment_id' => 'COM14',
                'user_id' => 'EST3',
                'contents' =>  "<p>Of course it’s a very important consideration! Scam and market maker brokers don’t allow withdrawal; since they trade against the traders!</p>",
                'created_at' => Carbon::now()->subDay(9)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM8',
                'comment_id' => 'COM15',
                'user_id' => 'EST2',
                'contents' =>  "<p>Well, I also started my trading profession as a part time trader; but now I am using this financial market as my main profession! I seem, a decent monthly return is very essential for the full time traders; yes Forex trading is challenging profession, but I am confident enough!</p>",
                'created_at' => Carbon::now()->subDay(9)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM8',
                'comment_id' => 'COM16',
                'user_id' => 'EST6',
                'contents' =>  "<p>Well, I seem Forex trading profession is the most flexible profession! This is way, I am here as a full time trader! Even, I spent more than 10 hours in a day when I was learning Forex business! Yes, I get enough financial freedom here, so no need any additional supports from others profession.</p>",
                'created_at' => Carbon::now()->subDay(11)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM9',
                'comment_id' => 'COM17',
                'user_id' => 'EST3',
                'contents' =>  "<p>Giving up is not an option when you determine to make profit and be success in forex. The successful traders in forex has also experience huge loss at a point in their trade but with confidence and great effort in one self there will be smile at the end of the day.</p>",
                'created_at' => Carbon::now()->subDay(2)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM9',
                'comment_id' => 'COM18',
                'user_id' => 'EST5',
                'contents' =>  "<p>I have never met a big time forex trader who never lost huge amounts of money. It's like no pain no gain. You can learn to walk without falling too much. And I think most people quit because they see forex a some sort of get-rich-quick kind of thing. This is not the case. So they fail a few couple of times, then they quit.</p>",
                'created_at' => Carbon::now()->subDay(4)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM10',
                'comment_id' => 'COM19',
                'user_id' => 'EST2',
                'contents' =>  "<p>Yeah...Smtimes I'm just thinking its all about the psychology... It's like when u r just in a class you are doin good and at the test - u fail. Maybe its because of pressure..I hope u see my point</p>",
                'created_at' => Carbon::now()->subDay(6)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM10',
                'comment_id' => 'COM20',
                'user_id' => 'EST1',
                'contents' =>  "<p>In demo your real money is not involved so you will not attach your emotion to it so even when you lose you are not at loss. But when it comes to live trading and you need to deposit money your emotion set in,and that fear and greed for profit will start affecting your trading output.</p>",
                'created_at' => Carbon::now()->subDay(12)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM11',
                'comment_id' => 'COM21',
                'user_id' => 'EST1',
                'contents' =>  "<p>I agree with your opinion on robot trading! In my early stage of trading, I used so many trading Robots but no consistent result! Basically, new traders don’t know the proper way of trading and scammers are very active on Social Media, so they easily attract the new traders! Here, without own trading skill, success is really impossible.</p>",
                'created_at' => Carbon::now()->subDay(8)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM11',
                'comment_id' => 'COM22',
                'user_id' => 'EST4',
                'contents' =>  "<p>Well, I don’t have so called daily, weekly target! But of course, I have a plan! I always try to follow my plan & strategy so honestly.</p>",
                'created_at' => Carbon::now()->subDay(2)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM12',
                'comment_id' => 'COM23',
                'user_id' => 'EST2',
                'contents' =>  "<p>Well, financial markets are risky in general. Whoever participate it knows the associated risks (not necessarily overlooking at them). However, financial markets are not done just for speculation. The good way of using financial instruments is to hedge against market controversial fluctuations.</p>",
                'created_at' => Carbon::now()->subDay(4)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM12',
                'comment_id' => 'COM24',
                'user_id' => 'EST4',
                'contents' =>  "<p>I totally agree , many people are lured into trading by the fact that trading can make you rich overnight . They start trading without understanding the underlying risks that they are exposed to while they trade. Specially something like a forex market is known for the risks associated with it . So traders should always consider the risk they are exposed to when they start trading. Jumping off to trade just considering the returns and ignoring the risks is definitely not a good sign in the long run.</p>",
                'created_at' => Carbon::now()->subDay(8)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM13',
                'comment_id' => 'COM25',
                'user_id' => 'EST6',
                'contents' =>  "<p>Definitely we can. Just you need to stand up super early to read all news.</p>",
                'created_at' => Carbon::now()->subDay(4)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM13',
                'comment_id' => 'COM26',
                'user_id' => 'EST4',
                'contents' =>  "<p>Yeah, right. We must know the news about Forex so that when we trade, we can get bigger profits..</p>",
                'created_at' => Carbon::now()->subDay(1)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM14',
                'comment_id' => 'COM27',
                'user_id' => 'EST3',
                'contents' =>  "<p>Normally, humans have this tendency to always win big. This has led to unnecessary risk when doing business. However, in order to play it safe while trading, a trader needs to set a target. This could be monthly, weekly or daily targets. Depending on the size of his account, a trader can set 2% or 5% weekly profit. Others can decide to set how much they are willing to risk while trading, so that when opening a trade, that is the amount they will invest. Therefore, whether it turned out good or bad, a trader will still be able to stay in business. Setting a target is a wise step for every trader.</p>",
                'created_at' => Carbon::now()->subDay(10)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM14',
                'comment_id' => 'COM28',
                'user_id' => 'EST6',
                'contents' =>  "<p>Trading safely is required as Market trading is totally dependent on generating profit or loss.So its required that you should take care while trading..</p>",
                'created_at' => Carbon::now()->subDay(10)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM14',
                'comment_id' => 'COM29',
                'user_id' => 'EST2',
                'contents' =>  "<p>The analyst and the analyst again. This is the best safest strategy.</p>",
                'created_at' => Carbon::now()->subDay(1)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM14',
                'comment_id' => 'COM30',
                'user_id' => 'EST5',
                'contents' =>  "<p>As an option to make ur trade more safe, u can use experts or advisors. Some brokers even have such service as copying of signals. I'm sure u r aware of that. Just connect ur deposit to the leaders of the world trading, and all their transactions will be duplicated on ur account. Copying trading signals is automatic, so ur account will be running non-stop without ur participation. U can choose one professional, or create an entire team that will make it for u. The Broker with whom I'm trading almost a year just began to provide this service and I'm very glad that they did it. Cheers</p>",
                'created_at' => Carbon::now()->subDay(13)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM15',
                'comment_id' => 'COM31',
                'user_id' => 'EST1',
                'contents' =>  "<p>Sign up for a demo account from some popular Forex broker. Learning from demo trading is one of the best ways to start Forex trading.</p>",
                'created_at' => Carbon::now()->subDay(10)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM15',
                'comment_id' => 'COM32',
                'user_id' => 'EST4',
                'contents' =>  "<p>Thorough learning is the key to success for making money with Forex trading. You need to learn a new set of skills. You cannot expect just to turn on the computer, trade some currencies and make a profit. You need to practice. You can do this by paper trading. You will need a broker account in order to start placing currency transactions. Find a broker who will first give you access to a demo account. This way you can simulate placing real trades without risking any of your hard earned cash. Practicing like this is the only way you will learn how to make a profit. Only when you are making consistent profits in your paper trading should you begin to use your own funds and place real deals.</p>",
                'created_at' => Carbon::now()->subDay(4)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM16',
                'comment_id' => 'COM33',
                'user_id' => 'EST2',
                'contents' =>  "<p>To be a good trader check this points:</p><ol><li>Start with Demo Account</li><li>Set Goals</li><li>Follow a Forex Trading Strategy</li><li>Manage Risk</li><li>Do Your Research</li><li>Be a Patient Trader</li><li>Don't Overtrade</li><li>Find a Trading Style That Fits Your Personality</li></ol>",
                'created_at' => Carbon::now()->subDay(2)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM16',
                'comment_id' => 'COM34',
                'user_id' => 'EST6',
                'contents' =>  "<p>There is no specific answer, it depends on your dedication & determinations level; for me, it took almost 1 year to make my 1st profit.</p>",
                'created_at' => Carbon::now()->subDay(1)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM17',
                'comment_id' => 'COM35',
                'user_id' => 'EST4',
                'contents' =>  "<p>You nailed it! This is why, now I always open my trading chart after 15-20 minutes meditation; it helps me a lot to build a better version of brain.</p>",
                'created_at' => Carbon::now()->subDay(6)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM17',
                'comment_id' => 'COM36',
                'user_id' => 'EST3',
                'contents' =>  "<p>Well said - thanks for posting!</p>",
                'created_at' => Carbon::now()->subDay(4)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM18',
                'comment_id' => 'COM37',
                'user_id' => 'EST6',
                'contents' =>  "<p>It is Unwise to borrow money to trade Forex. It is risky even more for a new trader. There is a higher probability that the money would be lost in a short time.</p>",
                'created_at' => Carbon::now()->subDay(20)->format('Y-m-d H:i:s')
            ],
            [
                'forum_id' => 'FOM18',
                'comment_id' => 'COM38',
                'user_id' => 'EST4',
                'contents' =>  "<p>It can hardly be called good, considering you're just starting forex trading. I recommend you trade with the sum that you're not afraid to lose.</p>",
                'created_at' => Carbon::now()->subDay(11)->format('Y-m-d H:i:s')
            ]
        ]);
    }
}
