@extends('layouts.default')
@section('content')

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="csrf-token" content="{{ csrf_token() }}">


<div style="margin: 20px;margin-bottom: 20px;margin-top: 130px;height: 680px;">
    <div class="row" style="height: 680px;margin-right: 0px;margin-left: 0px;">
        @include('elearning.side-nav')
        <div class="col-md-6 col-xl-10 offset-xl-0 sidenav-con" style="margin-bottom: 0px;margin-left: 0px;margin-top: 0px;height: 1880px;">
            <div class="sidenav-content-details">
            <h3 id="learning-title">Fundamental Analysis Introduction</h3>
            <img src ="{{asset('pictures/Fundamental.png')}}" class="img-padding" >
            <p>The term fundamental analysis refers to the study of tangible information about a market such as supply and demand statistics and expectations about what these numbers might be. Markets are a two-way street: Supply and demand are key factors in determining price, and price often is factor in supply and demand.</p>
            <p>Supply and demand comes from the perceived value that is placed on a stock, commodity, or any derivative product. In its simplest definition, supply is the amount of a given stock, product, or commodity that is available to the market, either in excess or limited at a given price depending on the number of sellers. Price establishes a resistance level when the supply of a particular product or stock is adequately provided.</p>
            <p>Demand, the amount of buying or lack of buying, plays an integral role in establishing how high or low prices can go and is generated by buyers. Demand establishes a support level for prices.</p>
            <p>Numerous event directly affect the outcome of both supply and demand, but some are more critical than others. For example, for agriculture products from grains to livestock, weather is a crucial element in determining supply. In the event of a drought, grain production could be in short and livestock could suffer weight loess or be forced to market in large numbers if it appears scarce feed may become too expensive. In harsh winters, grain movement could be slowed and livestock could perish, resulting in supply disruptions that could causes prices to go higher in a steady or rising demand environment.</p>
            <h5>Report</h5>
            <p>One of the advantages of trading futures is that the government releases dozens of reports every week, and the media provides additional material that offers insights into what might lie ahead for market prices. Determining the direction of the economy from reading economic reports is vital for understanding the potential for the direction of interest rates as well as gauging the health of the various sectors of the economy.</p>
            <p>For example, government reports such as those on employment may reveal what the potential for future household disposable income is and give analysts and economists an idea of how much spending could occur based on the number of Americans working. News articles give you the ability to follow and understand the political scene, both on international and domestic levels. If Congress passes a bill to donate more wheat than expected, then this action may have a more bullish impact of the price of wheat futures. Or if Congress passes laws to change the tax rate on capital gains, you might be able to speculate on what the stock market or other financial markets may do.</p>
            <p>If the European Central Bank announces a lower than expected interest rate adjustment, it is likely to affect the value of the euro and, inversely, the U.S. dollar. If values of these currencies shift abruptly and to a sever degree, then, of course, products that are imported and exported would be priced differently and, ultimately, could cause a ripple effect on costs and prices of goods and services in the United States and overseas.</p>
            <p>One reason you want to be educated an up-to-date on developments in the economy is because they usually dictate how different financial products and futures prices will perform. The stock market likes to see healthy economic growth because that usually equates to better or substantially larger corporate profits. The bond market prefers a slower, more sustainable growth rate that will not lead to inflationary pressures. By watching and tracking economic data and getting insights from analysts and economists, investors will be better able to keep in tune with the markets and their investments.</p>
            <p>In fact, you should be aware of what could happen before most reports are released. That is why news services often give the schedule for current events and special reports. Most futures brokerage firms also provide special calendars that include the dates and times that most major economic and agricultural reports are released.</p>
            <p>Trading is not an easy venture, and you should always be aware of the day’s current events and scheduled reports if you are in the markets. Not knowing what day or time a report is released could be hazardous to your financial health. Knowing about a major report before it is released is often useful because you have a chance to eliminate a surprise from an adverse market move. Even if you are not a fundamental trader, you should, at the very least, be aware of the main fundamental factors that might affect the markets you are trading and the impact reports and event may have on the market.</p>
            <p>*Adapted from "<b>A Complete Guide to Technical Trading Tactics</b>" by <b>John L. Person</b></p>
        </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{{ URL::asset('js/elearning.js')}}"></script>   
@stop